---
###############################################################################
################################# INSTALL #####################################
###############################################################################


# - debug: var=preexisting


- name: Add default ad lists for gravity DB
  template:
    src: adlists.list
    dest: "{{container_prefix}}/etc/adlists.list"
    mode: 0600
    owner: "{{container_user}}"
    group: "{{container_group}}"

- name: Add default custom dns lists
  template:
    src: custom.list.j2
    dest: "{{container_prefix}}/etc/custom.list"
    mode: 0600
    owner: "{{container_user}}"
    group: "{{container_group}}"
