---
###############################################################################
################################# INSTALL #####################################
###############################################################################

- stat:
    path: "{{ container_prefix }}"
  register: installed_ok
  tags:
    - container_systemd

- block:
  - name: create the tld  paths
    file:
      path: "{{ container_prefix }}/"
      state: directory
      mode: 0755
      owner: "{{container_user}}"
      group: "{{container_group}}"
  - name: create the conf paths
    file:
      path: "{{ container_conf_dir }}"
      state: directory
      mode: 0755
      owner: "{{container_user}}"
      group: "{{container_group}}"
  - name: create the data  paths
    file:
      path: "{{ container_prefix }}/data"
      state: directory
      mode: 0755
      owner: "{{container_user}}"
      group: "{{container_group}}"
  - name: create the log  paths
    file:
      path: "{{ container_prefix }}/log"
      state: directory
      mode: 0755
      owner: "{{container_user}}"
      group: "{{container_group}}"

  when: installed_ok.stat.exists == true


###############################################################################
################################ Initial Pull ####################################
###############################################################################


- name: Pull latest container image
  shell: "{{podman_path}} pull {{ image_name }}"
  args:
    executable: /bin/bash
  register: pull_ok
  become_user: "{{container_user}}"
  become: true
- debug:
   msg: "{{pull_ok}}"



###############################################################################
################################ Add envfile ####################################
###############################################################################

- block:

  - name: Add envfile for {{container}}
    template:
      src: container.envfile.j2
      dest: "{{container_env_file}}"
      mode: 0600
      owner: "{{container_user}}"
      group: "{{container_group}}"
    #notify: restart container



  become: yes
  become_user: "root"
  tags: container_systemd
