
###############################################################################
################################ Initial Pull ####################################
###############################################################################





- name: Add envfile for {{container}}
  template:
    src: container.envfile.j2
    dest: "{{container_env_file}}"
    mode: 0600
    owner: "{{container_user}}"
    group: "{{container_group}}"
- name: create the log  paths
  file:
    path: "{{ container_prefix }}/etc/dnsmasq.d"
    state: directory
    mode: 0755
    owner: "{{container_user}}"
    group: "{{container_group}}"
