---
###############################################################################
################################ Turn Up Systemd ####################################
###############################################################################

- block:


  - name: configure container for systemd
    template:
      src: container.service.j2
      dest: "{{ systemd_dir }}/{{service_name}}.service"
      mode: 0600
      owner: "{{container_user}}"
      group: "{{container_group}}"

    notify: reload systemd

  - name: enable container
    service:
      name: "{{ service_name }}"
      enabled: yes
      state: started

  become: yes
  become_user: "root"
  tags: container_systemd
